# Generated by Django 5.2.4 on 2026-07-21 20:32

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Chunk.embedding is a pgvector column, so the extension must exist first.
    dependencies = [
        ("core", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('total_claims', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('graph_state', models.JSONField(blank=True, default=dict)),
                ('cache_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('section', models.CharField(blank=True, db_index=True, max_length=120)),
                ('text', models.TextField()),
                ('char_start', models.PositiveIntegerField(default=0)),
                ('char_end', models.PositiveIntegerField(default=0)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
            ],
            options={
                'ordering': ['filing', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('origin', models.CharField(choices=[('llm', 'LLM'), ('user', 'User')], default='llm', max_length=10)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['thesis', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cik', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('supported', 'Supported'), ('contradicted', 'Contradicted'), ('insufficient_evidence', 'Insufficient evidence')], db_index=True, max_length=24)),
                ('explanation', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='ledger.chunk')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ledger.claim')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ledger.analysisjob')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['claim', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filing_type', models.CharField(choices=[('10-K', '10-K'), ('10-Q', '10-Q')], db_index=True, max_length=10)),
                ('period_end', models.DateField()),
                ('filed_at', models.DateField()),
                ('accession_number', models.CharField(max_length=25, unique=True)),
                ('source_url', models.URLField(max_length=500)),
                ('raw_text', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='ledger.company')),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddField(
            model_name='chunk',
            name='filing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ledger.filing'),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('claims_generated', 'Claims generated'), ('approved', 'Approved'), ('analyzed', 'Analyzed')], db_index=True, default='draft', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theses', to='ledger.company')),
            ],
            options={
                'verbose_name_plural': 'theses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ledger.thesis'),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='ledger.thesis'),
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.UniqueConstraint(fields=('company', 'filing_type', 'period_end'), name='unique_filing_per_period'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('filing', 'ordinal'), name='unique_chunk_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('thesis', 'ordinal'), name='unique_claim_ordinal'),
        ),
    ]
